Resources:
  # Account Table
  AccountTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AWS::StackName}-Accounts"
      BillingMode: "PROVISIONED"
      KeySchema:
        - KeyType: "HASH"
          AttributeName: "AccountId"
      AttributeDefinitions:
        - AttributeName: "AccountId"
          AttributeType: "S"
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  # Transaction Table
  TransactionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AWS::StackName}-Transactions"
      BillingMode: "PROVISIONED"
      KeySchema:
        - KeyType: "HASH"
          AttributeName: "TransactionId"
      AttributeDefinitions:
        - AttributeName: "TransactionId"
          AttributeType: "S"
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  # Entry Table
  EntryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AWS::StackName}-Entries"
      BillingMode: "PROVISIONED"
      KeySchema:
        - KeyType: "HASH"
          AttributeName: "EntryId"
      AttributeDefinitions:
        - AttributeName: "EntryId"
          AttributeType: "S"
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  # Token Table
  TokenTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AWS::StackName}-Tokens"
      BillingMode: "PROVISIONED"
      KeySchema:
        - KeyType: "HASH"
          AttributeName: "TokenId"
      AttributeDefinitions:
        - AttributeName: "TokenId"
          AttributeType: "S"
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  SubtotalTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AWS::StackName}-Subtotal"
      BillingMode: "PROVISIONED"
      KeySchema:
        - KeyType: "HASH"
          AttributeName: "SubtotalId"
      AttributeDefinitions:
        - AttributeName: "SubtotalId"
          AttributeType: "S"
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

# Stack Outputs
Outputs:
  StackArn:
    Value: !Ref AWS::StackId
    Description: Stack Id
